# install jdk 1.8
- name: Update the software package repository
  yum:
    name: '*'
    update_cache: yes


- name: Install dependencies
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - java-1.8.0-openjdk
    - git
    - texlive-latex
    - wget

- name: Download jenkins repo
  command: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo

- name: Import jenkins CI key
  rpm_key:
    key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present

- name: Update the software package repository
  yum:
    name: '*'
    update_cache: yes

- name: Install jenkins
  yum:
    name: jenkins
    state: latest
    update_cache: yes




- name: Allow port 8080
  shell: iptables -I INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT

- name: start the server
  service:
    name: jenkins
    state: started
- name: Print key
  shell: cat < /var/lib/jenkins/secrets/initialAdminPassword
- wait_for:
  port: 8080



# 
# yum remove java
# yum install java-1.8.0-openjdk

# install jenkins
#
# sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
# sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
# sudo yum install jenkins

# install git
# https://luvunix.wordpress.com/2017/10/03/jenkins-deployment-using-ansible/

# sudo cat **/var/lib/jenkins/secrets/initialAdminPassword**




